import { useState } from "react"
import { FormField } from "../components/FormField";
import { Loader } from "../components/Loader";
import { Card } from "../components/Card";
import { RenderCards } from "../components/RenderCards";

export const Home = () => {

    const [ loading, setLoading ] = useState(false);
    const [ allPosts, setAllPosts ] = useState([]);
    const [ searchText, setSearchText ] = useState("abc");

    return (
        <section className="max-w-7xl mx-auto"> 
            <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]">
                    The Community Showcase
                </h1>
                <p className="mt-2 text-[#666e75] text-[16px]">
                    Browse through a collection of imaginative and visually stunning images generated by LLM
                </p>
            </div>

            <div className="mt-16">
                <FormField />
            </div>

            <div className="mt-10">
                { loading ? (
                    <div className="flex justify-center items-center">
                        <Loader />
                    </div>
                ):<>
                    {searchText && (
                        <h2 className="font-medium text-[#666e75] text-xl mb-3"> 
                            Showing resut for <span className="text-[#222328] ">
                                {searchText}
                            </span>
                        </h2>
                    )}

                    <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3 ">
                        { searchText ? (
                            <RenderCards data={[]} title="No search result found"/>
                        ) : ( 
                            <RenderCards data={[]} title="No post found"/>
                        )}
                    </div>
                </>}
            </div>

        </section>
    )
}
